### ISSUE TITLE
piwigo-videojs on windows (7) now it works

### ISSUE THREAD

**Issue by photonensammler** [xbgmsharp/piwigo-videojs#45]
After my comment on https://github.com/xbgmsharp/piwigo-videojs/issues/42 I have more hours spent ty trying why I can't upload on Windows videos as normal photos. My explanations in the old comments are not quite right. The right solution I have found and want to explain it here. I hope that it will be useful to the Piwigo developers and give notes for her updates.

The declaration refers to piwigo 2.7.3 with VideoJS 2.7.a.

In /plugins/piwigo-videojs/include/functions_sync2.php must the single quotes in front of and behind the file/pathnames changed to double quotes. 
Which is important for Windows when a blank is in the pathname. 
All 4 lines in the source, where ffmpeg is called must be corrected to:

$ffmpeg = $sync_options['ffmpeg'] . " -itsoffset -" . $sync_options['postersec'] . " -i \"" . $in . "\" -vcodec mjpeg -vframes 1 -an -f rawvideo -y \"" . $out . '"';

For videos without exif-data must the source-part, that the MySql-table updated, corrected to:
isset($sync_options['batch_manager']) ? $infos[] = $filename . ' metadata: ' . implode(",", array_keys($exif)) : '';
  $sync_arr['metadata'] = count($exif) . " " . implode(",", array_keys($exif));
  if ($sync_options['metadata'] and ! $sync_options['simulate']) {
    $dbfields = explode(",", "filesize,width,height,latitude,longitude,date_creation,rotation");
    $dbset = vjs_dbSet($dbfields, $exif);
    $dbset = ($dbset !== FALSE && $dbset != '') ? ($dbset . ',') : '';
    $query = "UPDATE " . IMAGES_TABLE . " SET " . $dbset . " date_metadata_update=CURDATE() WHERE id=" . $row['id'] . ";";          //print $query;
    pwg_query($query);

In /plugins/piwigo-videojs/include/mediainfo.php must the mediainfo-call corrected to double-quotes (like the ffmpeg call):
  $output = shell_exec($sync_options['mediainfo'] . " --Full --Output=XML --Language=raw \"" . $filename . "\"");

In /admin/include/functions_upload.inc.php I have changed the function pwg_image_infos($path).
This is necessary because getimagesize() on php on windows no width and height for mp4 files returns. To determine the sizes, I use ffmpeg if getimiagesize() does not work:
(I use the newest ffmpeg version N-69060-gcd960c8 Copyright (c) 2000-2015 the FFmpeg developers  built on Jan 14 2015 22:13:45 with gcc 4.9.2 (GCC))

function pwg_image_infos($path) {
  global $conf;
  $size = getimagesize($path);
  if (($size === FALSE || $size == 0) && isset($conf['vjs_sync'])) { //use ffmpeg 
$ffmpeg = unserialize($conf['vjs_sync']);
    $ffmpeg_return = shell_exec($ffmpeg['ffmpeg'] . ' -i "' . $path . '" -vstats 2>&1');
    $regex_sizes = "/\s([0-9]{1,4})x([0-9]{1,4})\s/";
    preg_match($regex_sizes, $ffmpeg_return, $regs);
    $size = explode('x', $regs[0]);
  }
  $filesize = floor(filesize($path) / 1024);
  list($width, $height) = $size;
  return array(
      'width' => $width,
      'height' => $height,
      'filesize' => $filesize,
  );
}

With these changes VideoJS an Piwigo works perfectly on my windows server.
I have another piwigo installation on a Qnap system (any Linux version). 
There VideoJS works without all these changes, but I do not know why 
because I have very little knowledge of linux.
I hope I could help many windows-users.

Photonensammler

**Comment by zaphod82** [comment]
I had the same issue.  Being able to use this with both *nix and Win would be great, as Piwigo supports both.  The above changes works on my windows install.

One comment I would make though, could you please specify the line numbers for the changes.  It would be easier to find.

**Comment by photonensammler** [comment]
I'm still working on changes that work on windows and linux (I have restartet).
But there are so many changes and improvements that I'm not all can present here.
In a few days I'm done, how can I upload files here (sorry, but I am not familiar with github)?
I agree if the author of piwigo-js accepts the changes and a new version for all piwigo user makes disposal.

If my version on windows and linux error free, I'll find a possibility to make the changed files available for download (for a short time it will be possible).

Today I have a version finished, that works on linux perfect (including the generation of thumbnails every x seconds with preview images in the video).
Now I have this version only to adjust for Windows, then everything is finished. 

Because the generation of thumbnails with ffmpeg (thumbnail for preview in in the video) may need a long time, therefore is in the script  the possibility for the thumbnail generation in the background.
The script then ends even before all thumbnails generated.
But this possibility requires significantly more processing power and RAM.
The user can choose what he wants, background or normal generation (change a variable in the script).

I rise in some days when my changes are done and all works.

**Comment by photonensammler** [comment]
Now all works on Windows and Linux !
Video upload and generating thumbnails for video preview.

FFmpeg can run in a silent mode in background because the thumbnail generation needs a long time for long videos. Please read the readme_XX.txt file in the download package.

For a short time you can download the changed files from
http://photonensammler.homedns.org/piwigo-videojs-new/piwigo_videojs_new_sources.7z

In the archive are also ffmpeg and mediainfo (for Windows 32bit and 64bit) in the version included, with which I have programmed and tested. Therefore needs the file to download 46MB.

If anyone find errors in the sources, please report it direct with email (the address is in the readme_XX.txt) or write it here.

Much success and fun with Piwigo-VideoJS !
Photonensammler

**Comment by xbgmsharp** [comment]
I will accept the change. A pull request would have make thing easier.
https://help.github.com/articles/using-pull-requests/
I personally don't have any windows to test.
My development box and home server are all Linux.
I will look at your code.
Thanks for the help.

**Comment by photonensammler** [comment]
Hello xbgmsharp,

 

I would be delighted if you check my changes and take in your plugin.

The programming was for me a lot of fun :).

 

In the Linux version of your plugins was another error.
You have created the thumbnails with the wrong file name.
You've used the original name of the uploaded video. But the right name for the thumbnails is the name under which the video is stored in the /upload directory.

 

With mediainfo are signifikant differences between Linux and Windows (see in mediainfo.php).

The Windows version of mediainfo returns in the XML-Object e.g. “$general->Format__________________________”

The Linux version returns “$general->Format”.

 

On Windows all entries are 32 characters long, right padded with a underline.

So I have mediainfo for Windows in my 7z file. Maybe this is not a new version of the program so.

 

Greetings,

Photonensammler

 

 

 

 

 

 

Von: xbgmsharp [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Februar 2015 17:47
An: xbgmsharp/piwigo-videojs
Cc: photonensammler
Betreff: Re: [piwigo-videojs] piwigo-videojs on windows (7) now it works (#45)

 

I will accept the change. A pull request would have make thing easier.
https://help.github.com/articles/using-pull-requests/
I personally don't have any windows to test.
My development box and home server are all Linux.
I will look at your code.
Thanks for the help.

**Comment by xbgmsharp** [comment]
This is because of MediaInfo bug. [mediainfo:bugs] #886 XML Output broken
You should not use the latest version of MediaInfo.

**Comment by photonensammler** [comment]
Yesterday I downloaded my version from the official site to check if I had the right version.

I used the official release from https://mediaarea.net/nn/MediaInfo/Download/Windows ...the 64bit CLI version v0.7.72 for Windows.

 

Von: xbgmsharp [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Februar 2015 18:15
An: xbgmsharp/piwigo-videojs
Cc: photonensammler
Betreff: Re: [piwigo-videojs] piwigo-videojs on windows (7) now it works (#45)

 

This is because of MediaInfo bug. [mediainfo:bugs] #886 XML Output broken
You should not use the latest version of MediaInfo.

**Comment by xbgmsharp** [comment]
Version 0.7.72 is the buggy one and should not be used.
Install Version 0.7.71 or lower until the bug is fix.

**Comment by photonensammler** [comment]
But I think, that every Windows user, who wants to use the piwigo-videojs plugin at the moment will be download the "current" version from the mediainfo page.
When there is a new version of mediainfo, you (or I) adapt mediainfo.php ... or the medianfo version is in the source checked ?
That this is a bug in mediainfo, I did not.

**Comment by xbgmsharp** [comment]
I commit a version check for MediaInfo to avoid v0.7.72.
I report the issue a few months ago but still waiting on the next release which also delay the next release of the plugin.
I add a note on the release to let people know.

**Comment by xbgmsharp** [comment]
I commit a fix for empty metadata d21f5c8

**Comment by xbgmsharp** [comment]
I don't see why you need to change the PWG core. The width and height are base on the poster not from the MP4 file.
> In /admin/include/functions_upload.inc.php I have changed the function pwg_image_infos($path).
> This is necessary because getimagesize() on php on windows no width and height for mp4 files returns.

**Comment by photonensammler** [comment]
I had in this query mysql-errors because heigt and width were empty (not 0, but empty).
I've been looking for the cause width the debugger and saw that getimagesize is called with the file name of the video.
Therefore I have the dimension determined using ffmpeg, which then also works for me.

**Comment by photonensammler** [comment]
Sorry, I can't testing.
Tomorrow morning I'm going for a week in the holidays

**Comment by xbgmsharp** [comment]
Width is done on 
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L163
Height is done on
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L167

No sure where is the call for ``getimagesize`` but it is a different problem.

I just add an extra test to avoid empty value via 6dc3fbd thanks.

**Comment by photonensammler** [comment]
I'm back from holidays and have begun tests on windows.
For video upload I use the web form in the admin menu (Photos - Add), with a small video named test_9mb.mp4.
Just before the upload of the video is done the function 
add_uploaded_file("./upload/buffer\test_9mb.mp4", "test_9mb.mp4", .....
is called  (in /admin/include/functions_upload.inc.php).
This function calls $file_infos = pwg_image_infos("././upload/2015/02/28/20150228204355-3b12953d.mp4"); 
In this function is getimagesize with the mp4 video used, that does not work (see my changes in this function, I use ffmepg).
Further tests I could not perform because my mediainfo version is 0.7.72 (the official release from https://mediaarea.net/de/MediaInfo/Download). On the Mediainfo page is no download link to an older version.
It is not a satisfactory solution, to give the user only a hint that he used the wrong version of mediainfo. Can you please add a download link for the correct Mediainfo version ?
I hope that there will soon be a new version in which the bug is eliminated.

**Comment by xbgmsharp** [comment]
Thanks for getting back to me.
To download the correct version, you just have to change the version number.
For example for a Windows x64 version:
```
http://mediaarea.net/download/binary/mediainfo/0.7.72/MediaInfo_CLI_0.7.72_Windows_x64.zip
```
to 
```
http://mediaarea.net/download/binary/mediainfo/0.7.71/MediaInfo_CLI_0.7.71_Windows_x64.zip
```
What text/message would you display?

I updated the MediaInfo ticket, https://sourceforge.net/p/mediainfo/bugs/886/ and http://sourceforge.net/p/mediainfo/bugs/888/ 

For ``getimagesize`` issue on windows I reported the problem to the PWG team.
See http://piwigo.org/bugs/view.php?id=3208

**Comment by xbgmsharp** [comment]
I committed 2 fixed that should:
- Prevent the ``getimagesize()`` issue on Windows. It avoid waiting for a fix in PWG core
- Improve MediaInfo version issue message.

Please test and feedback.
If all good, I should be able to release a new version.

**Comment by photonensammler** [comment]
I tested with my changes for getimagesize () in /admin/include/functions_upload.inc.php.

Line 50 in mediainfo.php I have removed.

First test with buggy Mediainfo 0.7.72 ->
.....several screen pages with php warnings.
Warning: imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: in C:\.....\plugins\piwigo-videojs\include\function_frame.php on line 56
... and other error messages due to the first error

Then, as expected, your error message
Please DO NOT use MediaInfo version 0.7.72 due to Important known bug: XML output is broken
Upgrade or downgrade
Please refer to the documentation

Next test with Mediinfo 0.7.71
Your plugin error message
Error thumbnail running ffmpeg, try it manually:
    C:/......./ffmpeg/bin/ffmpeg.exe -itsoffset -0 -i './upload/2015/03/03/20150303180552-3b12953d.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -s 120x68 -y './upload/2015/03/03/pwg_representative/20150303180552-3b12953d-th_0.jpg'

...and then the detailed message
file: ./upload/2015/03/03/20150303180552-3b12953d.mp4
    metadata: 15 format,formatprofile,codecid,type,filesize,duration,playtime_seconds,date_creation,bitrate,width,height,display_aspect_ratio,frame_rate,channel,sampling_rate
    poster: ./upload/2015/03/03/pwg_representative/20150303180552-3b12953d.jpg
    overlay: add movie frame on ./upload/2015/03/03/pwg_representative/20150303180552-3b12953d.jpg
    thumbnail:
        0 seconds ./upload/2015/03/03/pwg_representative/20150303180552-3b12953d-th_0.jpg

The error message occurs because the ffmpeg command has single quoted the in and out filenames.
Line 235 (and line 238) in	/plugins/piwigo-videojs/include/functions_sync2.php must changed from

$ffmpeg = $sync_options['ffmpeg'] ." -itsoffset -".$second." -i '".$in."' -vcodec mjpeg -vframes 1 -an -f rawvideo -s ".$sync_options['thumbsize']." -y '".$out. "'";

to

$ffmpeg = $sync_options['ffmpeg'] . " -itsoffset -" . $second . " -i \"" . $in . "\" -vcodec mjpeg -vframes 1 -an -f rawvideo -s " . $sync_options['thumbsize'] . " -y \"" . $out . '"';

The ffmpeg command line should look like in windows so
C:/......./ffmpeg/bin/ffmpeg.exe -itsoffset -0 -i "./upload/2015/03/03/20150303180552-3b12953d.mp4" -vcodec mjpeg -vframes 1 -an -f rawvideo -s 120x68 -y "./upload/2015/03/03/pwg_representative/20150303180552-3b12953d-th_0.jpg"

...and not so
C:/....../ffmpeg/bin/ffmpeg.exe -itsoffset -0 -i './upload/2015/03/03/20150303180552-3b12953d.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -s 120x68 -y './upload/2015/03/03/pwg_representative/20150303180552-3b12953d-th_0.jpg'

After this changes ffmpeg is running properly.
I think that these changes must also be considered in function_sync.php ?

I do not know if I have already communicated to ... for mediainfo and ffmpeg on windows must the full path are entered in program dependencies when the programs not in the enviroment path.
Please consider this hints in your documentation for the new plugin version.

Can you please send me an email to joerg at photonensammler.de so that I have your real mail address?
I have a problem with a linux installation of a new test system with linux and windows parallel on a pc.
I believe that you can help me because I am not well versed with linux.
The google search for the solution of this problems was not helpful.

Thanks
Jörg

**Comment by xbgmsharp** [comment]
Thanks for testing.
Did you update the repository first? I did change the code from quote to double via commit d5a243d a few days ago. However you have the new error message.

Also please note ``function_sync.php`` is deprecated. It is not used anymore. It use getID3 which is not embedded anymore. Maye I should remove the file.

**Comment by xbgmsharp** [comment]
Tested on Windows
> I can find no fault, everything works correctly.

**Comment by layanto** [comment]
I still have this issue on Windows. Uploading mp4 video resulted in SQL error due to width and height being empty. Using piwigo 2.7.4 and latest videojs plugin with mediainfo 0.7.77 from official mediainfo Windows release. Haven't had the chance to investigate further.

**Comment by layanto** [comment]
Do I need to install via git or does the version available from within piwigo include the fixes for Windows?

**Comment by layanto** [comment]
I replaced the videojs plugin installed via Piwigo admin with master.zip from github and still have problem with sql error due to empty width and height on Windows.

**Comment by layanto** [comment]
I believe the modification on getimagesize() in admin\include\ functions_upload.inc.php is still required. Not sure why working on Linux as PHP getimagesize() function is meant for image not video. The problem is with SQL insert statement on line 428 which will have empty width and height from pwg_image_infos() on line 399.

**Comment by layanto** [comment]
Definitely still issue with piwigo core trying to insert SQL with empty width and height causing SQL error as width and height fields are interger type. I modified admin\include\functions_upload.Inc.php to set width and height to 0 if they are not larger than 0. Videojs plugin will then override them with correct width and height during synchronisation.
